language: java
jdk:
  - oraclejdk8
script:
  - curl -s https://get.sdkman.io | bash
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install kotlin
  - kotlinc test.kt -include-runtime -d app.jar
  - java -jar app.jar
